### ISSUE TITLE
allennlp的版本不对，提示导入错误：No module named 'allennlp.data.tokenizers.word_splitter'

### ISSUE THREAD

**Issue by SihengLi99** [ha-lins/GEML-MDG#1]

**Comment by ha-lins** [comment]
Hi, thanks for your interest.

Could you pls provide the version of allennlp you installed? Pls make sure to install the given allennlp with the editable mode as:
```
cd ./allennlp
pip install --editable .
cd ..
```

**Comment by SihengLi99** [comment]
您好，我是用的您的方法，安装的您修改过的allennlp 0.9版本 www.611456 ***@***.*** 签名由 网易邮箱大师 定制 在2021年03月12日 20:18，Shuai Lin 写道： Hi, thanks for your interest. Could you pls provide the version of allennlp you installed? Pls make sure to install the given allennlp with the editable mode as: cd ./allennlp pip install --editable . cd .. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SihengLi99** [comment]
> Hi, thanks for your interest.
> 
> Could you pls provide the version of allennlp you installed? Pls make sure to install the given allennlp with the editable mode as:
> 
> ```
> cd ./allennlp
> pip install --editable .
> cd ..
> ```

**Comment by SihengLi99** [comment]
> Hi, thanks for your interest.
> 
> Could you pls provide the version of allennlp you installed? Pls make sure to install the given allennlp with the editable mode as:
> 
> ```
> cd ./allennlp
> pip install --editable .
> cd ..
> ```

您可以查看一下您github中带的allennlp，并没有allennlp.data.tokenizers.word_splitter这个文件
