### ISSUE TITLE
按照您的方法安装了allennlp，但是您git中带的allennlp并没有allennlp.data.tokenizers.word_splitter这个文件，因此提示导入错误：No module named 'allennlp.data.tokenizers.word_splitter' (#1)

### ISSUE THREAD

**Issue by SihengLi99** [ha-lins/GEML-MDG#2]

**Comment by 1033020837** [comment]
同问

**Comment by ha-lins** [comment]
Hi @SihengLi99 @1033020837,

Sorry for my carelessness and the missed files have been uploaded. [commit](https://github.com/ha-lins/GEML-MDG/blob/master/allennlp/allennlp/data/tokenizers/word_splitter.py)
